---
agimus_controller_node:
  ros__parameters:
    ocp:
      dt: 0.01
      horizon_size: 10
      dt_factor_n_seq:
        n_steps: [7, 3]
        factors: [1, 2]
      armature: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
      max_qp_iter: 200
      max_iter: 20
      activate_callback: false
      termination_tolerance: 0.0001
    publish_debug_data: true
    constant_delay: false
    rate: 100.0
    free_flyer: false
    collision_as_capsule: true
    self_collision: false
    collision_pairs_names: [cp_1]
    cp_1:
      first: fer_hand_sc_capsule_0
      second: obstacle1_capsule_0
    robot_attachment_frame: universe